Bug fixes and improvements

diff --git a/.config/zsh/aliases b/.config/zsh/aliases
--- a/.config/zsh/aliases
+++ b/.config/zsh/aliases
@@ -41,14 +41,13 @@ mkvlan() {
 }
 
 source /Volumes/meouch/home/${USER}/private.env
-
+mf_mounts="$HOME/.config/zsh/macfuse_mounts.ishfs"
 ishfs() {
         if [ -z "$1" ]; then
-                mount | rg -e ${l_vol}$l_home -e ${l_vol}$l_sdd1 -e ${l_vol}$l_sdc1
-                return 1
+                mount | rg -Pe "(?:)(.Vol)(.*?)(?=\s\(macfuse)" -o
         fi
         for i in "$@"; do
-            mount | rg $i > /dev/null 2>&1; echo $?
+            cat $mf_mounts | rg $i > /dev/null 2>&1; echo $?
         done
 }
 
@@ -63,7 +62,7 @@ mountr() {
                 echo "${l_vol}$item is already mounted"
             fi
         done
-        mount | rg -Pe "(?:)(.Vol)(.*?)(?=\s\(macfuse)" -o > macfuse_mounts.tmp
+        $(ishfs) > $mf_mounts
     else
         echo "Invalid argument."
     fi
@@ -73,53 +72,35 @@ mountr() {
 # mount > /dev/null 2>&1 | rg -Pe "(?:)(.Vol)(.*?)(?=\s\(macfuse)" -o > macfusemounts.tmp > /dev/null 2>&1
 
 umountr() {
-    if [[ ! -f macfuse_mounts.tmp ]]; then
-        mount | rg -Pe "(?:)(.Vol)(.*?)(?=\s\(macfuse)" -o > macfusemounts.tmp; echo $?
-        if [[ $? -eq 0 ]]; then
-            echo "macfuse_mounts.tmp created"
-        else
-            echo "Error creating macfuse_mounts.tmp. Are you sure you have macfuse volumes mounted?"
+    if [ -z "$1" ]; then
+        if [[ ! -f $mf_mounts ]]; then
+            $(ishfs) > $mf_mounts
+        fi
+        if [[ ! -s $mf_mounts ]]; then
+            $(ishfs) > $mf_mounts
+            echo "There aren't any SSHFS volumes currently mounted, though if there should be, check the file $mf_mounts"
+            echo "If there are volumes that should be mounted, try running umountr again."
+            echo "If umountr fails to find any volumes mounted again, check lsof for sshfs for open files, or try restarting Finder."
+            echo "If all else fails, try restarting the computer."
             return 1
         fi
-
-    fi
-    if [ -z "$1" ]; then
-        while read -r line; do
-            if [[ $(ishfs ${line}) == 0 ]]; then
+        if [[ -s $mf_mounts ]]; then
+            while read -r line; do
                 echo "Unmounting $line"
-                umount ${line}
-            else
-                echo "${line} is not mounted."
-            fi
-        done < macfusemounts.tmp
+                umount ${line}; echo $?
+                if [[ $? -eq 0 ]]; then
+                    echo "Successfully unmounted $line"
+                    rm $mf_mounts
+                elif [[ $? -eq 1 ]]; then
+                    echo "Unmounting failed. Check lsof for sshfs for open files, or try restarting Finder."
+                    return 1
+                fi
+            done < "$mf_mounts"
     else
         echo "Invalid argument."
     fi
-
 }
-    #     umount_array=($l_home $l_sdd1 $l_sdc1)
-    #     sudo killall Finder
-    #     open /System/Library/CoreServices/Finder.app
-    #     for item in "${umount_array[@]}"; do
-    #         if [[ $(ishfs $item) -eq 0 ]]; then
-    #             echo "Unmounting ${l_vol}$item"
-    #             umount ${l_vol}$item > /dev/null 2>&1
-    #             if [[ $(echo $?) -eq 0 ]]; then
-    #                 echo "Unmounted ${l_vol}$item"
-    #             else
-    #                 echo "Failed to unmount ${l_vol}$item"
-    #             fi
-    #         else
-    #             echo "${l_vol}$item is not mounted"
-    #         fi
-    #     done
-    # else
-    #     echo "Invalid argument."
-    # fi
-#}
-
-#alias sshfsrg="$(mount | $(rg -e ${l_home_mount} -e ${l_sdd1} -e ${l_sdc1}))"
-
+    
 alias ls="exa --all --git --header --long --sort=.name --icons --octal-permissions --no-permissions --group-directories-first --tree -L=1"
 alias lss="exa --all --git --header --long --sort=mod --icons --octal-permissions --no-permissions --group-directories-first --tree -L=2"
 alias lsss="exa --all --git --header --long --sort=mod --icons --octal-permissions --no-permissions --group-directories-first --tree -L=3"
